FORMAT: 1A
HOST: http://private-9473c-marionguyen.apiary-mock.com/

# API cho hệ thống Loop.vn

Tài liệu đặc tả chi tiết các API được sử dụng trong hệ thống Loop.vn.

## Ngân hàng câu hỏi [/questions]

### Liệt kê các câu hỏi [GET]
Mỗi câu hỏi trả về sẽ bao gồm các thuộc tính sau:
- problemHierachy: Phân hệ kiến thức
- problemName: Mã của đơn vị kiến thức 
- questionTypeId: Id của kiểu câu hỏi (mặc định = 1 cho tất cả các câu hỏi trong dự án Loop)
- difficulty: Độ khó của câu hỏi (1-4)
- options: Danh sách các câu trả lời (option)
- isAnswer: Đáp án đúng sai
- isActive: Trạng thái hoạt động của câu hỏi
- solution: Đáp án của câu hỏi
Ngoài ra, bộ câu hỏi cũng được đính kèm các thiết lập (config) để tuy biến:
- richText: cho phép nhập nội dung dạng Richtext (để sẵn cho phần học Tiếng Anh)
- showClock: Hiển thị đồng hồ

+ Response 200 (application/json)
```
{
  "id": 1,
  "problemHierachy": "Hình học"
  "problemCode": "HHCB",
  "description": "Hình học cơ bản (Hình vuông, hình chữ nhật, hình tam giác...)",
  "config": {
    "richText": false,
    "showClock": false,
    "theme": "none"
  },
  "questions": [
    {
      "id": 1010,
      "name": "Hình nào dưới đây có 4 cạnh bằng nhau?",
      "difficulty": 1,
      "solution":"Đáp án đúng là hình vuông",
      "options": [
        {
          "id": 1055,
          "questionId": 1010,
          "name": "Vuông",
          "isAnswer": true
        },
        {
          "id": 1056,
          "questionId": 1010,
          "name": "Chữ nhật",
          "isAnswer": false
        },
        {
          "id": 1057,
          "questionId": 1010,
          "name": "Thoi",
          "isAnswer": false
        },
        {
          "id": 1058,
          "questionId": 1010,
          "name": "Thang",
          "isAnswer": false
        }
      ]
    },
    {
      "id": 1011,
      "name": "Hình tam giác có mấy cạnh?",
      "difficulty": 2,
      "solution":"Đáp án đúng là hình tam giác có 3 cạnh",
      "options": [
        {
          "id": 1055,
          "questionId": 1010,
          "name": "1",
          "isAnswer": false
        },
        {
          "id": 1057,
          "questionId": 1010,
          "name": "2",
          "isAnswer": false
        },
        {
          "id": 1056,
          "questionId": 1010,
          "name": "3",
          "isAnswer": true
        },
        {
          "id": 1058,
          "questionId": 1010,
          "name": "4",
          "isAnswer": false
        }
      ]
    },
    {
      "id": 1012,
      "name": "Tìm chu vi của hình vuông có cạnh bằng 8",
      "difficulty": 3,
      "solution":"Chu vi hình vuông bằng tổng độ dài 4 cạnh = 8*4=32 ",
      "options": [
        {
          "id": 1055,
          "questionId": 1010,
          "name": "12",
          "isAnswer": false
        },
        {
          "id": 1057,
          "questionId": 1010,
          "name": "16",
          "isAnswer": false
        },
        {
          "id": 1056,
          "questionId": 1010,
          "name": "18",
          "isAnswer": false
        },
        {
          "id": 1058,
          "questionId": 1010,
          "name": "32",
          "isAnswer": true
        }
      ]
    }
  ]
}
```
### Tạo câu hỏi mới [POST]

Người nhập liệu sẽ sử dụng API để tạo câu hỏi mới trong ngân hàng. 

+ Request (application/json)
```
    {
      "id": 1010,
      "name": "Hình nào dưới đây có 4 cạnh bằng nhau?",
      "difficulty": 1,
      "options": [
        {
          "id": 1055,
          "questionId": 1010,
          "name": "Vuông",
          "isAnswer": true
        },
        {
          "id": 1056,
          "questionId": 1010,
          "name": "Chữ nhật",
          "isAnswer": false
        },
        {
          "id": 1057,
          "questionId": 1010,
          "name": "Thoi",
          "isAnswer": false
        },
        {
          "id": 1058,
          "questionId": 1010,
          "name": "Thang",
          "isAnswer": false
        }
      ]
    }
```
+ Response 201 (application/json)

    + Headers

            Location: /questions/1
            
    + Body
```
    {
      "id": 1010,
      "name": "Hình nào dưới đây có 4 cạnh bằng nhau?",
      "difficulty": 1,
      "solution":"Đáp án đúng là hình vuông",
      "options": [
        {
          "id": 1055,
          "questionId": 1010,
          "name": "Vuông",
          "isAnswer": true
        },
        {
          "id": 1056,
          "questionId": 1010,
          "name": "Chữ nhật",
          "isAnswer": false
        },
        {
          "id": 1057,
          "questionId": 1010,
          "name": "Thoi",
          "isAnswer": false
        },
        {
          "id": 1058,
          "questionId": 1010,
          "name": "Thang",
          "isAnswer": false
        }
      ]
    }
```

## Lưu kết quả [/answer/log]
Mỗi câu trả lời sẽ được gửi đi và cập nhật vào hệ thống như sau:
- studentId: Mã học sinh
- problemHiearchy: Id của phân hệ kiến thức
- problemId: Id của đơn vị kiến thức
- problemView: Tổng số lần gặp lại câu hỏi 
- stepId: Id của câu hỏi
- stepStartTime: Thời gian bắt đầu hiển thị câu hỏi 
- firstTransactionTime: Thời điểm đầu tiên chọn một đáp án
- correctTransactionTime: Thời điểm chọn đáp án đúng
- stepEndTime: Thời gian kết thúc (gửi câu hỏi)
- stepDuration (s): Thời gian hoàn thành câu hỏi (tính bằng giây)
- correctFirstAttempt: Trả lời đúng ngay lần đầu tiên (0/1 hoặc true/false)
- corrects: Tổng số lần đúng 
- incorrects: Tổng số lần sai